image: maven:3.9.8-eclipse-temurin-21
stages:
  - dockerize
  - prepare
  - run_tests
  - make_reports
  - deploy

# TODO: renable job later
#- notify

variables:
  ALLURE_RESULTS_DIR: target/allure-results
  ALLURE_REPORT_DIR: target/site/allure-maven-plugin
  URL_GITLAB: https://gitlab.com/
  BACKUP_HISTORY_DIR: backup/history
  API_URL:
    value: ""
    description: |
      L'URL de l'environnement à tester. Par exemple l'environnement de qualif,
      ou un environnement Openshift d'une issue en cours...
      Si cette variable n'est pas définie, alors un fallback vers l'environnement "master" sera utilisé.
  TARGET_API:
    value: "test1"
    description: L'API à tester.
    options:
      - "test1"
      - "test2"
  REPORT_DIR: "public/${CI_COMMIT_REF_NAME}/${CI_PIPELINE_ID}"
  INDEX_FILE: "public/index.html"

cache:
  paths:
    - .m2/repository

# Docker image caching -> https://gitlab.com/augustin_bengolea/maven-e2e-archetype/container_registry
# https://docs.gitlab.com/ee/ci/docker/docker_layer_caching.html
prepare:
  stage: dockerize
  image: docker:24.0.5
  services:
    - docker:24.0.5-dind
  rules:
    - if: $CI_PIPELINE_SOURCE == "schedule"
    - if: $CI_PIPELINE_SOURCE == "web"
    - if: $UPDATE_MAVEN_IMAGE
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker pull maven:3.9.8-eclipse-temurin-21
    - docker tag maven:3.9.8-eclipse-temurin-21 $CI_REGISTRY_IMAGE/maven:3.9.8-eclipse-temurin-21
    - docker push $CI_REGISTRY_IMAGE/maven:3.9.8-eclipse-temurin-21

# TODO: maven package caching -> https://gitlab.com/augustin_bengolea/maven-e2e-archetype/-/packages
#   find the docs and the way of doing that

backup_history:
  stage: prepare
  script:
    - apt-get update && apt-get install -y unzip
    - chmod +x ./scripts/backup_allure_history.sh
    - ./scripts/backup_allure_history.sh
  artifacts:
    paths:
      - $BACKUP_HISTORY_DIR
    expire_in: 1 week

#TODO: variabiliser target.suite.xml.file pour obliger le choix entre telle ou telle API. Et mettre en place un fallback
tests:
  stage: run_tests
  script:
    - |
      mvn clean test -Dapi.url=${API_URL} \
                     -Dtarget.suite.xml.file=src/test/resources/testng/testng-jsonapi.xml
    - |
      if [ -d "$BACKUP_HISTORY_DIR" ] && [ "$(ls -A $BACKUP_HISTORY_DIR)" ]; then
        mkdir -p $ALLURE_RESULTS_DIR/history
        cp -rv $BACKUP_HISTORY_DIR/* $ALLURE_RESULTS_DIR/history/
      else
        echo "Aucun historique trouvé"
      fi
  # autoriser les erreurs (fail gracefully) pour les capturer dans le rapport Allure
  allow_failure: true
  artifacts:
    when: always
    paths:
      - $ALLURE_RESULTS_DIR/*
    expire_in: 1 week

generate_allure_report:
  stage: make_reports
  script:
    - mvn allure:report
  artifacts:
    when: always
    paths:
      - $ALLURE_RESULTS_DIR/*
      - $ALLURE_REPORT_DIR/*
    expire_in: 1 week


pages:
  stage: deploy
  script:
    - mkdir -p ${REPORT_DIR}
    - mv $ALLURE_REPORT_DIR/* ${REPORT_DIR}
    - cp -r public previous_public || true
    - chmod +x ./scripts/generate_index.sh
    - ./scripts/generate_index.sh
  artifacts:
    paths:
      - public
  only:
    - branches

#publish_email_report:
#  stage: notify
#  script:
#    - apt-get update && apt-get install -y curl jq
#    - REPORT_CONTENT=$(jq -sRr @json < mail_template/template.html)
#    - |
#      echo "{\"report\": $REPORT_CONTENT}" > payload.json
#    - |
#      curl -H 'Content-Type: application/json' -d @payload.json $WEBHOOK_TEAMS_REPORTING
