stages:
  - build_caches
  - run_tests
  - make_reports
  - deploy

variables:
  ALLURE_RESULTS_DIR: target/allure-results
  ALLURE_REPORT_DIR: target/site/allure-maven-plugin
  URL_GITLAB: https://gitlab.com/
  BACKUP_HISTORY_DIR: backup/history
  API_URL:
    value: ""
    description: |
      L'URL de l'environnement à tester. Par exemple l'environnement de qualif,
      ou un environnement Openshift d'une issue en cours...
      Si cette variable n'est pas définie, alors un fallback vers l'environnement "master" sera utilisé.
  TARGET_API:
    value: "test1"
    description: L'API à tester.
    options:
      - "test1"
      - "test2"
  REPORT_DIR: "public/${CI_COMMIT_REF_NAME}/${CI_PIPELINE_ID}"
  INDEX_FILE: "public/index.html"
  REPORTS_BASE_DIR: allure-reports
  SCRIPTS_DEBUG_MODE:
    value: "disabled"
    description: Enable debug mode. Useful when debugging bash scripts within the CI.
    options:
      - "enabled"
      - "disabled"

cache:
  key: "global-maven-cache"
  paths:
    - .m2/repository
  policy: pull-push

# Docker image caching
# Documentation :
# - https://docs.gitlab.com/ee/ci/docker/docker_layer_caching.
# - Build & Use Custom Docker images in your GitLab CI/CD pipeline : https://www.youtube.com/watch?v=7I6tHw68DMQ
# - https://dev.to/zenika/gitlab-ci-optimization-15-tips-for-faster-pipelines-55al#2-use-small-linux-distributions
build_docker_image:
  stage: build_caches
  image: docker:24.0.5
  services:
    - docker:24.0.5-dind
  rules:
    - if: '$CI_PIPELINE_SOURCE == "schedule"'
    - if: $CI_COMMIT_BRANCH
      changes:
        paths:
          - docker/**
  before_script:
    - echo "$CI_REGISTRY_PASSWORD" | docker login -u $CI_REGISTRY_USER $CI_REGISTRY --password-stdin
  script:
    - docker pull $CI_REGISTRY_IMAGE:latest || true

    - |
      docker build --build-arg BUILDKIT_INLINE_CACHE=1 \
      --cache-from $CI_REGISTRY_IMAGE:latest \
      --tag $CI_REGISTRY_IMAGE/lightweight:$CI_COMMIT_SHA \
      --tag $CI_REGISTRY_IMAGE/lightweight:latest \
      -f docker/lightweight/Dockerfile .
    - docker push $CI_REGISTRY_IMAGE/lightweight:$CI_COMMIT_SHA
    - docker push $CI_REGISTRY_IMAGE/lightweight:latest

    - |
      docker build --build-arg BUILDKIT_INLINE_CACHE=1 \
      --cache-from $CI_REGISTRY_IMAGE:latest \
      --tag $CI_REGISTRY_IMAGE/maven-java21:$CI_COMMIT_SHA \
      --tag $CI_REGISTRY_IMAGE/maven-java21:latest \
      -f docker/maven-java21/Dockerfile .
    - docker push $CI_REGISTRY_IMAGE/maven-java21:$CI_COMMIT_SHA
    - docker push $CI_REGISTRY_IMAGE/maven-java21:latest

# TODO: le backup pour la trendline ne marche plus - investiguer
#backup_history:
#  image: alpine:3.20.3
#  stage: prepare
#  before_script:
#    - apk add --no-cache bash curl unzip
#  script:
#    - chmod +x ./scripts/backup_allure_history.sh
#    - ./scripts/backup_allure_history.sh
#    - mkdir -p $REPORTS_BASE_DIR
#  artifacts:
#    paths:
#      - $BACKUP_HISTORY_DIR
#    expire_in: 1 week

#TODO: variabiliser target.suite.xml.file pour obliger le choix entre telle ou telle API. Et mettre en place un fallback
tests:
  image: $CI_REGISTRY_IMAGE/maven-java21:latest
  stage: run_tests
  rules:
    - if: '$CI_PIPELINE_SOURCE != "schedule"'
  script:
    - |
      mvn clean test -Dapi.url=${API_URL} \
                     -Dtarget.suite.xml.file=src/test/resources/testng/testng-jsonapi.xml \
                     -Dmaven.repo.local=$CI_PROJECT_DIR/.m2/repository
    - |
      if [ -d "$BACKUP_HISTORY_DIR" ] && [ "$(ls -A $BACKUP_HISTORY_DIR)" ]; then
        mkdir -p $ALLURE_RESULTS_DIR/history
        cp -rv $BACKUP_HISTORY_DIR/* $ALLURE_RESULTS_DIR/history/
      else
        echo "Aucun historique trouvé"
      fi
  # autoriser les erreurs (fail gracefully) pour les capturer dans le rapport Allure
  allow_failure: true
  artifacts:
    when: always
    paths:
      - $ALLURE_RESULTS_DIR/*
    expire_in: 1 week

generate_allure_report:
  image: $CI_REGISTRY_IMAGE/maven-java21:latest
  stage: make_reports
  rules:
    - if: '$CI_PIPELINE_SOURCE != "schedule"'
  script:
    - mvn allure:report -Dmaven.repo.local=$CI_PROJECT_DIR/.m2/repository
    - |
      if [ ! -d "$ALLURE_REPORT_DIR" ]; then
        echo "Allure report directory not found. Creating a dummy report."
        mkdir -p $ALLURE_REPORT_DIR
        echo "<html><body><h1>Allure Report</h1><p>Report generation failed. Please check the pipeline logs.</p></body></html>" > $ALLURE_REPORT_DIR/index.html
      fi
  artifacts:
    when: always
    paths:
      - $ALLURE_REPORT_DIR
      - $ALLURE_RESULTS_DIR/*
    expire_in: 1 week

pages:
  image: $CI_REGISTRY_IMAGE/lightweight:latest
  stage: deploy
  rules:
    - if: '$CI_PIPELINE_SOURCE != "schedule"'
  script:
    - git config --global user.name "GitLab CI automation"
    - git config --global user.email "augustin@bengolea.com"

    - rm -rf public

    - |
      git clone --depth 1 --branch pages \
        https://oauth2:${PAT_CI_CUSTOM_TOKEN}@${CI_SERVER_HOST}/${CI_PROJECT_PATH}.git public || mkdir public

    - mkdir -p public/reports/$CI_PIPELINE_ID
    - cp -r $ALLURE_REPORT_DIR/* public/reports/$CI_PIPELINE_ID

    - ls -la public/reports/$CI_PIPELINE_ID

    - chmod +x ./scripts/generate_report_specifics.sh
    - ./scripts/generate_report_specifics.sh

    - ls -la public/reports/$CI_PIPELINE_ID

    - cd public
    - git add .
    - git commit -m "[skip ci] Add report for pipeline $CI_PIPELINE_ID" || echo "No changes to commit"
    - git push https://oauth2:${PAT_CI_CUSTOM_TOKEN}@${CI_SERVER_HOST}/${CI_PROJECT_PATH}.git pages
  artifacts:
    paths:
      - public
